name: Clojure Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@12.5
      with:
        cli: 1.11.2.1446             # Clojure CLI based on tools.deps
        clj-kondo: 2022.05.31
        cljfmt: 0.10.2
        cljstyle: 0.15.0
        cmd-exe-workaround: 'latest'
        zprint: 1.2.3

    - name: Cache clojure dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: cljdeps-${{ hashFiles('deps.edn') }}
        restore-keys: cljdeps-

    - name: Install libassimp
      run: sudo apt-get update && sudo apt-get install -y libassimp-dev

    - name: Run tests
      run: clojure -M:dev:test
